# python -m src.ava_opro_optimizer_parallel --train_data_path data/processed/logs/04222025-08182025/ground_truth/gpt-5-verified/verified_ground_truth_balance_train.json --initial_prompt_file prompts/original/identify_partial.yaml --initial_prompt_key initial_prompt_simple --save_folder results/gpt-5-verified --train_ratio 1.0 --max_processes 4 --num_search_steps 100 --meta_prompt_key v1 --max_num_instructions 10
# python -m src.ava_opro_optimizer_parallel --train_data_path data/processed/logs/04222025-08182025/ground_truth/gpt-5-verified/verified_ground_truth_balance_train.json --initial_prompt_file prompts/original/identify_partial.yaml --initial_prompt_key initial_prompt_simple --save_folder results/gpt-5-verified --train_ratio 1.0 --max_processes 4 --num_search_steps 30 --meta_prompt_key v1 --max_num_instructions 10 --scorer_model gpt-4.1-mini --exp_mode random
python -m src.ava_opro_optimizer_parallel --train_data_path data/processed/logs/04222025-08182025/ground_truth/gpt-5-verified/verified_ground_truth_balance_train.json --initial_prompt_file prompts/original/identify_partial.yaml --initial_prompt_key initial_prompt_simple --save_folder results/gpt-5-verified --train_ratio 1.0 --max_processes 4 --num_search_steps 30 --meta_prompt_key v1 --max_num_instructions 10 --scorer_model gpt-4o-mini --exp_mode random
python -m src.ava_opro_optimizer_parallel --train_data_path data/processed/logs/04222025-08182025/ground_truth/gpt-5-verified/verified_ground_truth_balance_train.json --initial_prompt_file prompts/original/identify_partial.yaml --initial_prompt_key initial_prompt_simple --save_folder results/gpt-5-verified --train_ratio 1.0 --max_processes 4 --num_search_steps 30 --meta_prompt_key v1 --max_num_instructions 10 --scorer_model gpt-4.1 --exp_mode random
python -m src.ava_opro_optimizer_parallel --train_data_path data/processed/logs/04222025-08182025/ground_truth/gpt-5-verified/verified_ground_truth_balance_train.json --initial_prompt_file prompts/original/identify_partial.yaml --initial_prompt_key initial_prompt --save_folder results/gpt-5-verified --train_ratio 1.0 --max_processes 4 --num_search_steps 30 --meta_prompt_key v1 --max_num_instructions 10 --scorer_model gpt-4o-mini --exp_mode random
python -m src.ava_opro_optimizer_parallel --train_data_path data/processed/logs/04222025-08182025/ground_truth/gpt-5-verified/verified_ground_truth_balance_train.json --initial_prompt_file prompts/original/identify_partial.yaml --initial_prompt_key initial_prompt --save_folder results/gpt-5-verified --train_ratio 1.0 --max_processes 4 --num_search_steps 30 --meta_prompt_key v1 --max_num_instructions 10 --scorer_model gpt-4.1-mini --exp_mode random
python -m src.ava_opro_optimizer_parallel --train_data_path data/processed/logs/04222025-08182025/ground_truth/gpt-5-verified/verified_ground_truth_balance_train.json --initial_prompt_file prompts/original/identify_partial.yaml --initial_prompt_key initial_prompt --save_folder results/gpt-5-verified --train_ratio 1.0 --max_processes 4 --num_search_steps 30 --meta_prompt_key v1 --max_num_instructions 10 --scorer_model gpt-4.1 --exp_mode random
# python -m src.ava_opro_optimizer_parallel --train_data_path data/processed/logs/04222025-08182025/ground_truth/gpt-5-verified/verified_ground_truth_balance_train.json --initial_prompt_file prompts/original/identify_partial.yaml --initial_prompt_key initial_prompt --save_folder results/gpt-5-verified --train_ratio 1.0 --max_processes 4 --num_search_steps 30 --meta_prompt_key v1 --max_num_instructions 10 --scorer_model gpt-4.1-mini
# python -m src.ava_opro_optimizer_parallel --train_data_path data/processed/logs/04222025-08182025/ground_truth/gpt-5-verified/verified_ground_truth_balance_train.json --initial_prompt_file prompts/original/identify_partial.yaml --initial_prompt_key initial_prompt --save_folder results/gpt-5-verified --train_ratio 1.0 --max_processes 4 --num_search_steps 30 --meta_prompt_key v1 --max_num_instructions 10 --scorer_model gpt-4.1
# python -m src.ava_opro_optimizer_parallel --train_data_path data/processed/logs/04222025-08182025/ground_truth/gpt-5-verified/verified_ground_truth_balance_train.json --initial_prompt_file prompts/original/identify_partial.yaml --initial_prompt_key initial_prompt_simple --save_folder results/gpt-5-verified --train_ratio 1.0 --max_processes 4 --num_search_steps 100 --meta_prompt_key v1 --max_num_instructions 10 --scorer_model gpt-4.1-mini
# python -m src.ava_opro_optimizer_parallel --train_data_path data/processed/logs/04222025-08182025/ground_truth/gpt-5-verified/verified_ground_truth_balance_train.json --initial_prompt_file prompts/original/identify_partial.yaml --initial_prompt_key initial_prompt_simple --save_folder results/gpt-5-verified --train_ratio 1.0 --max_processes 4 --num_search_steps 30 --meta_prompt_key v2 --max_num_instructions 10 --old_instruction_score_threshold 0.85
# python -m src.ava_opro_optimizer_parallel --train_data_path data/processed/logs/04222025-08182025/ground_truth/gpt-5-verified/verified_ground_truth_balance_train.json --initial_prompt_file prompts/original/identify_partial.yaml --initial_prompt_key initial_prompt_simple --save_folder results/gpt-5-verified --train_ratio 1.0 --max_processes 4 --num_search_steps 30 --num_generated_instructions_in_each_step 8
# python -m src.ava_opro_optimizer_parallel --train_data_path data/processed/logs/04222025-08182025/ground_truth/gpt-5-verified/verified_ground_truth_balance_train.json --initial_prompt_file prompts/original/identify_partial.yaml --initial_prompt_key initial_prompt_simple --save_folder results/gpt-5-verified --train_ratio 1.0 --max_processes 4 --num_search_steps 30 --scorer_model gpt-4.1-mini
# python -m src.ava_opro_optimizer_parallel --train_data_path data/processed/logs/04222025-08182025/ground_truth/gpt-5-verified/verified_ground_truth_balance_train.json --initial_prompt_file prompts/original/identify_partial.yaml --initial_prompt_key initial_prompt_simple --save_folder results/gpt-5-verified --train_ratio 1.0 --max_processes 4 --num_search_steps 30 --scorer_model gpt-4.1